# Generated by Django 3.0.7 on 2020-08-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_auto_20200710_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role_employee',
            new_name='RoleEmployee',
        ),
    ]
