# Generated by Django 3.0.7 on 2020-07-04 03:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_card', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.AutoField(primary_key=True, serialize=False)),
                ('landlord', models.BooleanField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.House')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Person')),
            ],
        ),
    ]
